# Generated by Django 3.2.23 on 2023-11-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231031_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeystrokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=15)),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
    ]
